/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillingManagementSystem;
import Dao.ConnectionProvider;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
public class Billing extends javax.swing.JFrame {
        
    Connection con=null;
    public float finaltotal=0;
    
    public Billing() {
        
        initComponents();
        con=ConnectionProvider.getConnection();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        SimpleDateFormat df=new SimpleDateFormat("dd-mm-yy");
        Date date=new Date();
        lblDate.setText(df.format(date));
        
        DateTimeFormatter dtf;
        dtf =  DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        lblTime.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPamount = new javax.swing.JTextField();
        txtRamount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setText("Billing");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 24, 45, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 24, 85, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 63, 45, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 63, 85, -1));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1149, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Buyer Details:");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, -1, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name:");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 145, -1, 25));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 146, 158, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Conatct No:");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 145, -1, 25));

        txtContact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 146, 158, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 145, 58, 25));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 146, 172, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Address :");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 145, 74, 25));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 146, 186, 25));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 189, 1149, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Product Details:");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Product Id :");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 236, -1, 25));

        txtPid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPidActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 237, 58, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Product Name :");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 236, -1, 25));

        txtPname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 237, 150, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rate :");
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 236, -1, 25));

        txtRate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel1.add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 237, 76, 26));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Quantity :");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 236, -1, 25));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 237, 80, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Description :");
        kGradientPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 236, -1, 25));

        txtDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel1.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 237, 158, 25));
        kGradientPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 316, 1149, 10));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(Table);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 703, 270));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1052, 273, 69, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Calculation Details:");
        kGradientPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 332, -1, 25));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total :");
        kGradientPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 389, -1, 25));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 390, 153, 26));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Paid Amount :");
        kGradientPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 444, -1, 25));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Return Amount :");
        kGradientPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 496, -1, 25));

        txtPamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPamountActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtPamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 445, 153, 26));

        txtRamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kGradientPanel1.add(txtRamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 497, 153, 26));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1052, 389, 69, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 444, -1, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 496, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/billing.png"))); // NOI18N
        kGradientPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 16, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnameActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        try{
            String sql="select * from newbuyer where Name=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, txtName.getText());
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                txtName.setText(rs.getString("Name"));
                txtContact.setText(rs.getString("Contact"));
                txtEmail.setText(rs.getString("Email"));
                txtAddress.setText(rs.getString("Address"));
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, " Name doesn't exist");
        }
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        setVisible(false);
        new Billing().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        
         try{
            String sql="select * from newbuyer where Contact=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, txtContact.getText());
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                txtName.setText(rs.getString("Name"));
                txtContact.setText(rs.getString("Contact"));
                txtEmail.setText(rs.getString("Email"));
                txtAddress.setText(rs.getString("Address"));
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Contact doesn't exist");
        }
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        
        try{
            String sql="select * from newbuyer where Email=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, txtEmail.getText());
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                txtName.setText(rs.getString("Name"));
                txtContact.setText(rs.getString("Contact"));
                txtEmail.setText(rs.getString("Email"));
                txtAddress.setText(rs.getString("Address"));
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Email doesn't exist");
        }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPidActionPerformed
       
        try{
            String sql="select * from product where Pid=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, txtPid.getText());
            ResultSet rs=ps.executeQuery();
            
            if(rs.next()){
                txtPid.setText(rs.getString("Pid"));
                txtPname.setText(rs.getString("Pname"));
                txtRate.setText(rs.getString("Rate"));
                txtDesc.setText(rs.getString("Description"));
                txtQuantity.setText("1");
            }else{
                txtQuantity.setText("1");
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Product Id doesn't exist");
        }
    }//GEN-LAST:event_txtPidActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        float price=Float.parseFloat(txtRate.getText());
        int quantity=Integer.parseInt(txtQuantity.getText());
        Float total=price*quantity;
        DefaultTableModel model=(DefaultTableModel)Table.getModel();
        model.addRow(new Object[]{txtName.getText(), txtDesc.getText(), price, quantity, total});
         finaltotal= finaltotal+total;
        String finalTotal=String.valueOf(finaltotal);
        txtTotal.setText(finalTotal);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtPamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPamountActionPerformed
        // TODO add your handling code here:
        
        String paidAmount=txtPamount.getText();
        int z=Integer.parseInt(paidAmount);
        finaltotal=z-finaltotal;
        String finalTotal=String.valueOf(finaltotal);
        txtRamount.setText(finalTotal);
        txtRamount.setEditable(false);
        
        
    }//GEN-LAST:event_txtPamountActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String path="E:\\";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try
        {
           PdfWriter.getInstance(doc, new FileOutputStream(path+""+txtName.getText()+""+ lblDate.getText()+".pdf"));
           doc.open();
           Paragraph paragraph=new Paragraph("                      Shoap name billing\n                          contact No: 8298241734");
           doc.add(paragraph);
           Paragraph paragraph1=new Paragraph("Date & time: "+lblDate.getText()+" "+lblTime.getText()+" \nBuyer Details: \nName: "+txtName.getText()+"\nContact No: "+txtContact.getText()+"\nEmail: "+txtEmail.getText()+"\nAddress: "+txtAddress.getText()+ "\n\n");
           doc.add(paragraph1);
           
            PdfPTable tb1=new PdfPTable(5);
            tb1.addCell("Name");
            tb1.addCell("Description");
            tb1.addCell("Rate");
            tb1.addCell("Quantity");
            tb1.addCell("Sub total");
            
            for(int i=0; i<Table.getRowCount(); i++)
            {
                String n=Table.getValueAt(i, 0).toString();
                String d=Table.getValueAt(i, 1).toString();
                String r=Table.getValueAt(i, 2).toString();
                String q=Table.getValueAt(i, 3).toString();
                String t=Table.getValueAt(i, 4).toString();
                
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
                tb1.addCell(t);
            }
            doc.add(tb1);
            
            Paragraph pg=new Paragraph("\nTotal: " +txtTotal.getText()+"\nPaid Amount: "+txtPamount.getText()+"\nReturn Amount: "+txtRamount.getText()+"\nn Thanks for visiting Please come again\n");
            doc.add(pg);
            JOptionPane.showMessageDialog(null, "Pdf generated successfully");
            setVisible(true);
            new Billing().setVisible(true);

            
        }catch(DocumentException | FileNotFoundException e){
            
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPamount;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRamount;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
