/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillingManagementSystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PANDIT
 */
public class Home extends javax.swing.JFrame {
    
  public int z=0;
    public Home() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);

        
        btnNB.setVisible(false);
        btnDB.setVisible(false);
        btnBD.setVisible(false);
       // btnLogout.setVisible(false);
        btnUB.setVisible(false);
        btnNP.setVisible(false);
        btnPD.setVisible(false);
        btnUP.setVisible(false);
        btnDP.setVisible(false);
        btnBilling.setVisible(false);
       // btnClose.setVisible(false);
       
       lblNB.setVisible(false);
       lblDB.setVisible(false);
       lblBD.setVisible(false);
       lblAP.setVisible(false);
       lblUB.setVisible(false);
       lblUP.setVisible(false);
       lblPD.setVisible(false);
       lblDP.setVisible(false);
       lblBilling1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnHome = new javax.swing.JButton();
        btnNB = new javax.swing.JButton();
        btnBD = new javax.swing.JButton();
        btnDB = new javax.swing.JButton();
        btnUB = new javax.swing.JButton();
        btnNP = new javax.swing.JButton();
        btnUP = new javax.swing.JButton();
        btnPD = new javax.swing.JButton();
        btnDP = new javax.swing.JButton();
        lblNB = new javax.swing.JLabel();
        lblBD = new javax.swing.JLabel();
        lblUB = new javax.swing.JLabel();
        lblAP = new javax.swing.JLabel();
        lblUP = new javax.swing.JLabel();
        lblPD = new javax.swing.JLabel();
        lblDP = new javax.swing.JLabel();
        lblDB = new javax.swing.JLabel();
        btnBilling = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        lblBilling1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(0, 153, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/right-arrow.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 70, 70));

        btnNB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/add-user.png"))); // NOI18N
        btnNB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnNBComponentShown(evt);
            }
        });
        btnNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNBActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 70));

        btnBD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/detail buyer.png"))); // NOI18N
        btnBD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnBDComponentShown(evt);
            }
        });
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 80, 70));

        btnDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/delete_user.png"))); // NOI18N
        btnDB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnDBComponentShown(evt);
            }
        });
        btnDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 70, 70));

        btnUB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/update byer.png"))); // NOI18N
        btnUB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnUBComponentShown(evt);
            }
        });
        btnUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUBActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, 70));

        btnNP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/add product.png"))); // NOI18N
        btnNP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnNPComponentShown(evt);
            }
        });
        btnNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNPActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 70, 70));

        btnUP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/update_product.png"))); // NOI18N
        btnUP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnUPComponentShown(evt);
            }
        });
        btnUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 70, 70));

        btnPD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/product detail.png"))); // NOI18N
        btnPD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnPDComponentShown(evt);
            }
        });
        btnPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 70, 70));

        btnDP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/delete produt.png"))); // NOI18N
        btnDP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnDPComponentShown(evt);
            }
        });
        btnDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 70, 70));

        lblNB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNB.setText("New Buyer");
        kGradientPanel1.add(lblNB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, 30));

        lblBD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBD.setText("Buyer Detail");
        kGradientPanel1.add(lblBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 30));

        lblUB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUB.setText("Update Buyer");
        kGradientPanel1.add(lblUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, 30));

        lblAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAP.setText("Add Product");
        kGradientPanel1.add(lblAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 100, 30));

        lblUP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUP.setText("Update Product");
        kGradientPanel1.add(lblUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 100, 30));

        lblPD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPD.setText("Product Detail");
        kGradientPanel1.add(lblPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 100, 30));

        lblDP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDP.setText("Delete Product");
        kGradientPanel1.add(lblDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 100, 30));

        lblDB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDB.setText("Delete Buyer");
        kGradientPanel1.add(lblDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, 30));

        btnBilling.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/billing.png"))); // NOI18N
        btnBilling.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnBillingComponentShown(evt);
            }
        });
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 70, 70));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/close (1).png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 30, 70, 70));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/logout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 30, 70, 70));

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        kGradientPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 100, 80, 30));

        lblBilling1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBilling1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBilling1.setText("Billing");
        kGradientPanel1.add(lblBilling1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 70, 20));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("Close");
        kGradientPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 110, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
        // TODO add your handling code here:
        new BuyerDetails().setVisible(true);
    }//GEN-LAST:event_btnBDActionPerformed

    private void btnDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBActionPerformed
        // TODO add your handling code here:
        new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_btnDBActionPerformed

    private void btnUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUBActionPerformed
        // TODO add your handling code here:
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_btnUBActionPerformed

    private void btnNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNPActionPerformed
        // TODO add your handling code here:
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_btnNPActionPerformed

    private void btnUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPActionPerformed
        // TODO add your handling code here:
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_btnUPActionPerformed

    private void btnPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDActionPerformed
        // TODO add your handling code here:
        new ProductDetails().setVisible(true);
    }//GEN-LAST:event_btnPDActionPerformed

    private void btnDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnDPActionPerformed

    private void btnNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNBActionPerformed

         //setVisible(false);
        NewBuyer nb=new NewBuyer();
        nb.setVisible(true);
        
    }//GEN-LAST:event_btnNBActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

         
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
       if(z==0)
       {
            try{
            
                Thread.sleep(250);
                btnNB.setVisible(true);
                 lblNB.setVisible(true);
        }catch(InterruptedException e){
            
        }
       }else{
           
        btnNB.setVisible(false);
        btnDB.setVisible(false);
        btnBD.setVisible(false);
        btnUB.setVisible(false);
        btnNP.setVisible(false);
        btnPD.setVisible(false);
        btnUP.setVisible(false);
        btnDP.setVisible(false);
        btnBilling.setVisible(false);
        //btnClose.setVisible(false);
       //btnLogout.setVisible(true);
       
       lblNB.setVisible(false);
       lblDB.setVisible(false);
       lblBD.setVisible(false);
       lblAP.setVisible(false);
       lblUB.setVisible(false);
       lblUP.setVisible(false);
       lblPD.setVisible(false);
       lblDP.setVisible(false);
       lblBilling1.setVisible(false);
       
        z=0;
       }
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnNBComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnNBComponentShown
      try {
          // TODO add your handling code here:

          Thread.sleep(250);
           btnBD.setVisible(true);
          lblBD.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnNBComponentShown

    private void btnBDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnBDComponentShown
      try {
          // TODO add your handling code here:
          Thread.sleep(250);
           btnDB.setVisible(true);
          lblDB.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnBDComponentShown

    private void btnDBComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnDBComponentShown
      try {
          // TODO add your handling code here:
          
          Thread.sleep(250);
        btnUB.setVisible(true);
        lblUB.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnDBComponentShown

    private void btnUBComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnUBComponentShown
      try {
          // TODO add your handling code here:
          Thread.sleep(250);
          btnNP.setVisible(true);
          lblAP.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnUBComponentShown

    private void btnNPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnNPComponentShown
      try {
          // TODO add your handling code here:
          Thread.sleep(250);
         btnUP.setVisible(true);
          lblUP.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnNPComponentShown

    private void btnUPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnUPComponentShown
      try {
          // TODO add your handling code here:
          
          Thread.sleep(250);
          
           btnPD.setVisible(true);
           lblPD.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnUPComponentShown

    private void btnPDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnPDComponentShown
      try {
          // TODO add your handling code here:

          Thread.sleep(250);
         btnDP.setVisible(true);
          lblDP.setVisible(true);
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnPDComponentShown

    private void btnDPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnDPComponentShown
      try {
          // TODO add your handling code here:

          Thread.sleep(250);
           btnBilling.setVisible(true);
           lblBilling1.setVisible(true);
          z=1;
      } catch (InterruptedException ex) {
          Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnDPComponentShown

    private void btnBillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnBillingComponentShown
        
    }//GEN-LAST:event_btnBillingComponentShown


    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        // TODO add your handling code here:
        new Billing().setVisible(true);
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You want to close this application", "select", JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You want to close this application", "select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    
    
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBD;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDB;
    private javax.swing.JButton btnDP;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNB;
    private javax.swing.JButton btnNP;
    private javax.swing.JButton btnPD;
    private javax.swing.JButton btnUB;
    private javax.swing.JButton btnUP;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblBD;
    private javax.swing.JLabel lblBilling1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDB;
    private javax.swing.JLabel lblDP;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNB;
    private javax.swing.JLabel lblPD;
    private javax.swing.JLabel lblUB;
    private javax.swing.JLabel lblUP;
    // End of variables declaration//GEN-END:variables
}
