/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillingManagementSystem;

import Dao.ConnectionProvider;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author PANDIT
 */
public class Login extends javax.swing.JFrame {

    Connection con=null;
    public Login() {
        initComponents();
        
        con=ConnectionProvider.getConnection();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        //setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        checkboxShow1 = new javax.swing.JCheckBox();
        btnLogin1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        Regbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login Here");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, 340, 60));

        txtUserName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 360, 220, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("UseId");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 360, 100, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 430, 100, 28));

        txtPassword1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 430, 220, 27));

        checkboxShow1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkboxShow1.setText("Show Password");
        getContentPane().add(checkboxShow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 490, 220, 30));

        btnLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/login.png"))); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 540, 100, 30));

        btnClose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/close.png"))); // NOI18N
        btnClose1.setText("Close");
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 540, 100, 30));

        Regbtn1.setBackground(new java.awt.Color(255, 51, 51));
        Regbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regbtn1.setText("New User Register !");
        Regbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Regbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 600, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/banner image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 820));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/banner color.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 690, 780));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Shop Management System");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(580, 20, 482, 44);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingManagementSystem/close (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1440, 20, 69, 60);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You want to close this application", "select", JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Regbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regbtn1ActionPerformed
        // TODO add your handling code here:
        Registration r=new Registration();
        r.setVisible(true);
    }//GEN-LAST:event_Regbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regbtn1;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JCheckBox checkboxShow1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUserName1;
    // End of variables declaration//GEN-END:variables
}
